"""Basic wing sizing calculator for the VANT project.

This is a first-pass estimator for project notes. It uses simple textbook
relationships and assumes steady level flight at sea-level density by default.
The calculator is configured around takeoff performance, but can be easily modified to size for cruise or landing.
"""
##VARIABLES##
mass = 2.0 # mass of the aircraft in kg
velocity = 8 # takeoff velocity in m/s
angle_of_attack = 30 # angle of attack in degrees at takeoff
air_density = 1.225 # air density at sea level in kg/m^3
thrust = 20 # thrust available in Newtons at takeoff


##CALCULATIONS##
import math

lift_required = mass * 9.81 # lift required to balance weight in Newtons

#Thrust lift component
thrust_lift = thrust * math.sin(math.radians(angle_of_attack)) # component of thrust contributing to lift

#Wing lift component
wing_lift = lift_required - thrust_lift # lift that must be generated by the wings





##OUTPUTS##
print(f"Lift required: {lift_required:.2f} N")
print(f"Thrust lift component: {thrust_lift:.2f} N")
print(f"Wing lift component: {wing_lift:.2f} N")

